spring:
  datasource:
    url :
    username :
    password :
    driver-class-name: org.postgresql.Driver
    sql-script-encoding: utf-8
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format-sql: true

logging:
  level:
    org:
      hibernate.SQL: debug
      springframework.web: debug

login:
  retentionMinutes: 720

client:
  max_sec: 3600
  urls: http://localhost:3000, http://127.0.0.1:3000