spring:
  datasource:
    url :
    username :
    password :
    driver-class-name: org.postgresql.Driver
    sql-script-encoding: utf-8
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format-sql: true

logging:
  level:
    org:
      hibernate.SQL: debug
      springframework.web: debug

login:
  retentionMinutes: 720

client:
  max_sec: 3600
  urls: